{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" . }}
    {{- include "cray-service.common-labels" . | nindent 4 }}
    {{- with .Values.service.labels -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
  annotations:
    {{- include "cray-service.common-annotations" . | nindent 4 }}
    {{- if eq .Values.service.type "LoadBalancer" -}}
    metallb.universe.tf/address-pool: "{{ include "cray-service.metallb-address-pool" . }}"
    {{- if .Values.service.sharedIp }}
    metallb.universe.tf/allow-shared-ip: "{{ include "cray-service.boot-services-shared-ip" . }}"
    {{- end -}}
    {{- end -}}
    {{- with .Values.service.annotations -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: Cluster
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      name: {{ .name | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
