#
# MIT License
#
# (C) Copyright 2020, 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

sqlCluster:
  enabled: false
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/postgres
    tag: 13.2-alpine
    pullPolicy: IfNotPresent
  waitForItJob: true
  instanceCount: 3
  volumeSize: 1Gi
  #
  # Consumers of this chart can set pod priority for postgres pods as follows:
  #
  # podPriorityClassName: csm-high-priority-service
  users:
    service_account: []
  databases:
    service_db: service_account
  tls:
    enabled: true
    issuer: cert-manager-issuer-common
  connectionPooler:
    enabled: false
    instanceCount: 3
    mode: "session"
    image: artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/pgbouncer:master-21
    resources:
      requests:
        cpu: 500m
        memory: 300Mi
      limits:
        cpu: 1
        memory: 300Mi
  #
  # Consumers of this chart can override postgres cluster pod resource limits as follows:
  #
  # resources:
  #   limits:
  #     cpu: "1"
  #     memory: 500Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  resources: {}
  #
  # Consumers of this chart can override postgres parameters as follows:
  #
  # parameters:
  #   shared_buffers: "32MB"
  #   max_connections: "10"
  #   log_statement: "all"
  parameters: {}
  # Consumers of this chart can enable logical backups on a set schedule:
  enableLogicalBackup: false
  logicalBackupSchedule: "0 0 * * *"

global:
  appVersion: ""  # This is set at build time.
  # these are values to address shortcomings of helm in referencing .Chart.* values in sub-charts/parent charts:
  # https://github.com/helm/helm/issues/4314
  # https://github.com/helm/helm/issues/3920
  chart:
    name: ""  # set at deploy time automatically, no need to ever set explicitly
    version: ""  # set at deploy time automatically, no need to ever set explicitly
