apiVersion: v2
name: cray-service
version: 8.0.1
description: This chart should never be installed directly, base your specific Cray service charts off this one
home: https://github.com/Cray-HPE/base-charts
maintainers:
  - name: bklei
  - name: brantk-hpe
  - name: kburns-hpe
annotations:
  artifacthub.io/images: |
    - name: busybox
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/busybox:1.28.0-glibc
    - name: docker-kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: coreos/etcd
      image: artifactory.algol60.net/csm-docker/stable/quay.io/coreos/etcd:v3.3.22
    - name: postgres
      image: artifactory.algol60.net/csm-docker/stable/docker.io/library/postgres:13.2-alpine
    - name: acid/pgbouncer
      image: artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/pgbouncer:master-17
    - name: cray-postgres-db-backup
      image: artifactory.algol60.net/csm-docker/stable/cray-postgres-db-backup:0.2.0
  artifacthub.io/license: MIT
