#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
# Default values for cray-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appVersion: ""  # This is set at build time.
  # these are values to address shortcomings of helm in referencing .Chart.* values in sub-charts/parent charts:
  # https://github.com/helm/helm/issues/4314
  # https://github.com/helm/helm/issues/3920
  chart:
    name: ""  # set at deploy time automatically, no need to ever set explicitly
    version: ""  # set at deploy time automatically, no need to ever set explicitly

nameOverride: ""  # chart-wide naming prefix
fullnameOverride: ""  # use this if you want to provide a more-complete name prefix for certain labels/naming (very optional)

# Note that this base chart already applies standard labels and annotations by
# default, you only need to worry about adding your own if you have specific
# needs for labeling or annotating
labels: {}
annotations: {}

jobs: {}
  # myJob:
  #   # job metadata annotations can go here, namely for supporting setting Helm hooks, but any other annotations will be set as well
  #   annotations:
  #     helm.sh/hook: pre-install,pre-upgrade
  #     helm.sh/hook-weight: 1
  #     helm.sh/hook-delete-policy: before-hook-creation
  #   # standard job spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#jobspec-v1-batch)
  #   template:
  #     # standard pod spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podspec-v1-core)
  #     # except containers, initContainers, ephemeralContainers which we want to be objects instead of lists for easy overriding
  #     spec:
  #       containers:
  #         primary:
  #           # standard container spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#container-v1-core)
  #           image:
  #             repository: cray/my-job
