---
# Default values for cray-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagesHost: "dtr.dev.cray.com" # this value will always be set on helm install based on install context, this is a reasonable default
global:
  appVersion: "" # This is set at build time.
  # these are values to address shortcomings of helm in referencing .Chart.* values in sub-charts/parent charts:
  # https://github.com/helm/helm/issues/4314
  # https://github.com/helm/helm/issues/3920
  chart:
    name: "" # set at deploy time automatically, no need to ever set explicitly
    version: "" # set at deploy time automatically, no need to ever set explicitly

nameOverride: "" # chart-wide naming prefix
fullnameOverride: "" # use this if you want to provide a more-complete name prefix for certain labels/naming (very optional)

# Note that this base chart already applies standard labels and annotations by
# default, you only need to worry about adding your own if you have specific
# needs for labeling or annotating
labels: {}
annotations: {}

jobs: {}
  # myJob:
  #   # job metadata annotations can go here, namely for supporting setting Helm hooks, but any other annotations will be set as well
  #   annotations:
  #     helm.sh/hook: pre-install,pre-upgrade
  #     helm.sh/hook-weight: 1
  #     helm.sh/hook-delete-policy: before-hook-creation
  #   # standard job spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#jobspec-v1-batch)
  #   template:
  #     # standard pod spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podspec-v1-core)
  #     # except containers, initContainers, ephemeralContainers which we want to be objects instead of lists for easy overriding
  #     spec:
  #       containers:
  #         primary:
  #           # standard container spec fields supported (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#container-v1-core)
  #           # except for image, which we want to handle a bit differently to support overriding of image name, tag, use of imagesHost prefix, etc.
  #           image:
  #             repository: cray/my-job
