{{- if .Values.sealedSecrets -}}
{{- range $val := .Values.sealedSecrets }}
{{- if $val.kind }}
{{- if eq $val.kind "SealedSecret" }}
---
{{ toYaml $val }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
