{{/*
MIT License

(C) Copyright 2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
{{- if gt (len .Values.trsWorkers) 0 -}}
{{- $fullname := include "cray-service.fullname" . -}} 
{{- range .Values.trsWorkers }}
---
apiVersion: trs.hms.cray.com/v1alpha1
kind: TRSWorker
metadata:
  name: "{{ $fullname }}-{{ .workerType }}-{{ .workerVersion }}"
spec:
  worker_type: {{ .workerType | quote }}
  worker_version: {{ .workerVersion | quote }}
  worker_image_tag: {{ .workerImageTag | quote }}
{{- end }}

---
# The deployment using this TRSWorker really needs to wait for the topics to actually have been created before
# starting up. This is because in case the Kafka server is configured to allow topics to be created as they are used
# this would cause a conflict in the operator which would be bad.
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "cray-service.fullname" . }}-wait-for-kafka-topics-{{ .Release.Revision }}"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.fullname" . }}-wait-for-kafka-topics
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      # This service account is created in the TRS operator deployment.
      serviceAccountName: "kafka-topics-watcher"
      containers:
{{- range .Values.trsWorkers }}
{{- $trsWorkerName := print $fullname "-" .workerType "-" .workerVersion }}
        - name: "wait-for-kafka-topics-{{ .workerType }}-{{ .workerVersion }}"
          image: {{ $.Values.kubectl.image.repository }}:{{ $.Values.kubectl.image.tag }}
          imagePullPolicy: {{ $.Values.kubectl.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - while [ "`kubectl -n services get kafkatopics.kafka.strimzi.io trs-{{ $trsWorkerName }}-{{ .workerType }}-{{ .workerVersion }}-rcv -o jsonpath='{.status.conditions[0].type}'`" != "Ready" ]; do
              echo "Waiting for trs-{{ $trsWorkerName }}-{{ .workerType }}-{{ .workerVersion }}-rcv to be Ready";
              sleep 3;
              done;
              while [ "`kubectl -n services get kafkatopics.kafka.strimzi.io trs-{{ $trsWorkerName }}-{{ .workerType }}-{{ .workerVersion }}-send -o jsonpath='{.status.conditions[0].type}'`" != "Ready" ]; do
              echo "Waiting for trs-{{ $trsWorkerName }}-{{ .workerType }}-{{ .workerVersion }}-send to be Ready";
              sleep 3;
              done;
              echo "Kafka topics reported ready.";
{{- end }}
{{- end }}
