{{/*
MIT License

(C) Copyright [2022-2023] Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
{{- if .Values.sqlCluster.enabled -}}
{{- $root := . -}}
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: "{{ include "cray-postgresql.fullname" . }}-postgres"
  labels:
    app.kubernetes.io/name: {{ include "cray-postgresql.fullname" . }}-postgres
    {{- include "cray-postgresql.common-labels" . | nindent 4 }}
    {{- with .Values.sqlCluster.labels -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
spec:
  teamId: "{{ include "cray-postgresql.fullname" . }}"
  volume:
    size: {{ .Values.sqlCluster.volumeSize }}
  numberOfInstances: {{ .Values.sqlCluster.instanceCount }}
{{- if .Values.sqlCluster.podPriorityClassName }}
  podPriorityClassName: {{ .Values.sqlCluster.podPriorityClassName }}
{{- end }}
  {{- if .Values.sqlCluster.resources }}
  {{- with .Values.sqlCluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- end }}
  users:
    {{- with .Values.sqlCluster.users -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}
  databases:
    {{- with .Values.sqlCluster.databases -}}
    {{ toYaml . | nindent 4 -}}
    {{- end }}

  {{- if .Values.sqlCluster.connectionPooler.enabled }}
  enableConnectionPooler: true
  connectionPooler:
    numberOfInstances: {{ .Values.sqlCluster.connectionPooler.instanceCount }}
    mode: "{{ .Values.sqlCluster.connectionPooler.mode }}"
    dockerImage: "{{ .Values.sqlCluster.connectionPooler.image }}"
  {{- end }}

  postgresql:
    # This needs to line up with the spilo image in the cray-postgres-operator-chart.
    version: 14
    {{- if .Values.sqlCluster.parameters }}
    {{- with .Values.sqlCluster.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end -}}
    {{- end }}

  patroni:
    pg_hba:
    - local   all             all                             trust
    - hostssl all             +zalandos    127.0.0.1/32       pam
    - host    all             all          127.0.0.1/32       md5
    - host    all             all          127.0.0.6/32       md5
    - hostssl all             +zalandos    ::1/128            pam
    - host    all             all          ::1/128            md5
    - hostssl replication     standby      all                md5
    - hostnossl all           all          all                reject
    - hostssl all             +zalandos    all                pam
    - hostssl all             all          all                md5

{{- if .Values.sqlCluster.tls.enabled }}

  tls:
    secretName: "{{ include "cray-postgresql.fullname" $root }}-postgres-tls"
{{- end }}
{{- end }}
