name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: '20 13 * * *'
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      chart-dirs: kubernetes
      lint-and-test: ${{ github.event_name == 'pull_request' }}
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }
