name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: '20 13 * * *'
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      test-charts: ${{ github.event_name == 'pull_request' }}
      test-setup: |
        # Install Helm unittest plugin
        helm env
        helm plugin install https://github.com/quintush/helm-unittest

        # Install Istio
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.8.6 sh -
        cd istio-1.8.6
        export PATH=$PWD/bin:$PATH
        istioctl install --set profile=demo -y
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
