name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: '20 13 * * *'
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      test-charts: false
      lint-pre-script: |
        # Install Helm unittest plugin
        helm env
        helm plugin install https://github.com/quintush/helm-unittest
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
