name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: '20 13 * * *'
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint: ${{ github.event_name == 'pull_request' }}
      test: false
      ct-flags: --chart-dirs kubernetes --target-branch $GITHUB_BASE_REF
      ct-install-flags: --debug
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
